"""Compatibility facade for focused Coordination registry modules."""

from __future__ import annotations

from app.services.coordination_registry_common import (
    ARCHIVE_DETECT_METRICS_PATH,
    ARCHIVE_DISCOVER_DETAIL_ROOT,
    ARCHIVE_EVENT_ROOT,
    ARCHIVE_FUSION_DETAIL_ROOT,
    ARCHIVE_MANIFEST_PATH,
    ARCHIVE_ROOT,
    COORDINATION_EXPERIMENT_ROOT,
    DATASET_STORAGE_ROOT,
    MODEL_SIGNATURE,
    OBJECT_ID_RELATION_HINTS,
    PRETRAINED_CHECKPOINT_DETECT_EPOCHS,
    PRETRAINED_CHECKPOINT_HIDDEN_DIM,
    RELATION_LABELS,
    RUN_RELATIONS,
    RUN_STORAGE_ROOT,
    SYSTEM_ARCHIVE_DISCOVER_ENCODER,
    SYSTEM_ARCHIVE_GNN_BACKEND,
    SYSTEM_ARCHIVE_LM_BACKEND,
    SYSTEM_ARCHIVE_SEED,
    SYSTEM_ARCHIVE_SPLIT,
    SYSTEM_DATASET_CREATED_BY,
    _archive_detect_summary_map,
    _as_float,
    _coordination_runtime_config,
    _dataset_paths_from_record,
    _dataset_record,
    _json_dump,
    _json_load,
    _load_archive_result_pair,
    _resolve_archive_root,
    _resolve_coordination_experiment_root,
    _runnable_relations,
    _safe_json_loads,
    _slugify,
    _str_column,
    _system_archive_run_summary,
    _system_dataset_paths,
    _unique_dataset_slug,
    ensure_system_archive_datasets,
)

from app.services.coordination_result_projection import (
    _TOPWORD_STOPWORDS,
    _build_account_profile_map,
    _build_account_profile_url,
    _build_community_event_frame,
    _build_coordination_community_payload,
    _build_coordination_graph_payload,
    _build_relation_evidence,
    _build_result_snapshot,
    _cluster_key,
    _community_maps,
    _compact_top_objects,
    _compute_community_topwords,
    _default_dataset_platform,
    _enrich_top_object_item,
    _extract_douyin_aweme_id_from_url,
    _extract_note_id_from_post_url,
    _extract_object_evidence_examples,
    _extract_xhs_note_id_from_url,
    _format_top_object_item,
    _infer_relation_from_object_id,
    _is_raw_shared_object,
    _load_dataset_event_frame,
    _load_run_result_pair,
    _normalize_platform_name,
    _normalize_text_cell,
    _prediction_maps,
    _relation_label,
    _resolve_shared_object_text,
    _safe_score,
    _sort_cluster_value,
    _tokenize_topwords,
    _truncate_text,
)

from app.services.coordination_registry_repository import (
    _load_latest_result_context,
    _run_record,
    _summarize_event_table,
    create_coordination_run,
    get_coordination_community_detail,
    get_coordination_dataset_detail,
    get_coordination_dataset_graph,
    get_coordination_dataset_latest_result,
    get_coordination_run,
    list_coordination_datasets,
    upload_coordination_dataset,
)

from app.services.coordination_run_execution import (
    _execute_coordination_run,
    run_coordination_model_job,
)

__all__ = [
    "ARCHIVE_DETECT_METRICS_PATH",
    "ARCHIVE_DISCOVER_DETAIL_ROOT",
    "ARCHIVE_EVENT_ROOT",
    "ARCHIVE_FUSION_DETAIL_ROOT",
    "ARCHIVE_MANIFEST_PATH",
    "ARCHIVE_ROOT",
    "COORDINATION_EXPERIMENT_ROOT",
    "DATASET_STORAGE_ROOT",
    "MODEL_SIGNATURE",
    "OBJECT_ID_RELATION_HINTS",
    "PRETRAINED_CHECKPOINT_DETECT_EPOCHS",
    "PRETRAINED_CHECKPOINT_HIDDEN_DIM",
    "RELATION_LABELS",
    "RUN_RELATIONS",
    "RUN_STORAGE_ROOT",
    "SYSTEM_ARCHIVE_DISCOVER_ENCODER",
    "SYSTEM_ARCHIVE_GNN_BACKEND",
    "SYSTEM_ARCHIVE_LM_BACKEND",
    "SYSTEM_ARCHIVE_SEED",
    "SYSTEM_ARCHIVE_SPLIT",
    "SYSTEM_DATASET_CREATED_BY",
    "create_coordination_run",
    "ensure_system_archive_datasets",
    "get_coordination_community_detail",
    "get_coordination_dataset_detail",
    "get_coordination_dataset_graph",
    "get_coordination_dataset_latest_result",
    "get_coordination_run",
    "list_coordination_datasets",
    "run_coordination_model_job",
    "upload_coordination_dataset",
]
