"""Coordination Discover research-grade platform-generic pipeline."""

from .artifacts import (
    find_snapshot_artifact,
    load_discover_artifact,
    validate_manifest_for_snapshot,
    write_discover_artifact,
)
from .contracts import (
    AccountMultigraphEdge,
    FALLBACK_POLICY,
    MODALITY_POLICY,
    SEMANTIC_TEXT_EMBEDDING_FIELDS,
    COORDINATION_DISCOVER_MODEL_VERSION,
    COORDINATION_DISCOVER_TECHNOLOGY,
    DEPRECATED_COORDINATION_DISCOVER_MODEL_VERSIONS,
    DetectValidationRequest,
    DetectValidationResult,
    DiscoverResult,
    DynamicDiscoverRequest,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceObject,
    CoordinationDiscoverArtifactManifest,
    TemporalMAGNNConfig,
)
from .evidence import build_evidence_graph
from .models import (
    MODEL_INPUT_FEATURE_NAMES,
    PAIR_EDGE_FULL_ACCOUNT_LIMIT,
    PAIR_EDGE_MAX_PAIRS_PER_OBJECT,
    PAIR_EDGE_NEIGHBOR_LIMIT,
    TEXT_EMBEDDING_FEATURE_NAME,
    TemporalMAGNNTensors,
    build_account_pair_edges,
    build_temporal_magnn_tensors,
    fit_temporal_magnn,
    partition_learned_graph,
)
from .pipelines import export_coordination_result, run_detect_validation, run_dynamic_discover
from .process_experiments import build_process_causal_experiment_report

__all__ = [
    "AccountMultigraphEdge",
    "FALLBACK_POLICY",
    "COORDINATION_DISCOVER_MODEL_VERSION",
    "COORDINATION_DISCOVER_TECHNOLOGY",
    "CoordinationDiscoverArtifactManifest",
    "DEPRECATED_COORDINATION_DISCOVER_MODEL_VERSIONS",
    "MODALITY_POLICY",
    "MODEL_INPUT_FEATURE_NAMES",
    "PAIR_EDGE_FULL_ACCOUNT_LIMIT",
    "PAIR_EDGE_MAX_PAIRS_PER_OBJECT",
    "PAIR_EDGE_NEIGHBOR_LIMIT",
    "SEMANTIC_TEXT_EMBEDDING_FIELDS",
    "TEXT_EMBEDDING_FEATURE_NAME",
    "DetectValidationRequest",
    "DetectValidationResult",
    "DiscoverResult",
    "DynamicDiscoverRequest",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceObject",
    "TemporalMAGNNConfig",
    "TemporalMAGNNTensors",
    "build_account_pair_edges",
    "build_evidence_graph",
    "build_process_causal_experiment_report",
    "build_temporal_magnn_tensors",
    "export_coordination_result",
    "find_snapshot_artifact",
    "fit_temporal_magnn",
    "load_discover_artifact",
    "partition_learned_graph",
    "run_detect_validation",
    "run_dynamic_discover",
    "validate_manifest_for_snapshot",
    "write_discover_artifact",
]
