"""Coordination Discover research-grade platform-generic pipeline."""

from .artifacts import (
    find_snapshot_artifact,
    load_discover_artifact,
    validate_manifest_for_snapshot,
    write_discover_artifact,
)
from .contracts import (
    AccountMultigraphEdge,
    FALLBACK_POLICY,
    MODALITY_POLICY,
    SEMANTIC_TEXT_EMBEDDING_FIELDS,
    COORDINATION_DISCOVER_MODEL_VERSION,
    COORDINATION_DISCOVER_TECHNOLOGY,
    DEPRECATED_COORDINATION_DISCOVER_MODEL_VERSIONS,
    DetectValidationRequest,
    DetectValidationResult,
    DiscoverResult,
    DynamicDiscoverRequest,
    EvidenceEdge,
    EvidenceGraph,
    EvidenceObject,
    CoordinationDiscoverArtifactManifest,
    TemporalMAGNNConfig,
)
from .evidence import build_evidence_graph
from .models import (
    MODEL_INPUT_FEATURE_NAMES,
    PAIR_EDGE_FULL_ACCOUNT_LIMIT,
    PAIR_EDGE_MAX_PAIRS_PER_OBJECT,
    PAIR_EDGE_NEIGHBOR_LIMIT,
    TEXT_EMBEDDING_FEATURE_NAME,
    TemporalMAGNNTensors,
    build_account_pair_edges,
    build_temporal_magnn_tensors,
    fit_temporal_magnn,
    partition_learned_graph,
)
from .temporal_edge_model import (
    TemporalEdgeModelConfig,
    TemporalEdgeSplit,
    build_matched_hard_negatives,
    fit_temporal_edge_model,
    fit_temporal_edge_model_multi_seed,
    run_temporal_edge_ablation_suite,
    split_temporal_account_edges,
)
from .pipelines import export_coordination_result, run_detect_validation, run_dynamic_discover
from .process_experiments import build_process_causal_experiment_report
from .iohunter_temporal_edge_candidate import (
    DEFAULT_CANDIDATE_ABLATION_METRICS_FILENAME,
    DEFAULT_CANDIDATE_FAMILY,
    DEFAULT_CANDIDATE_METHOD,
    DEFAULT_CANDIDATE_METRICS_FILENAME,
    DEFAULT_CANDIDATE_SCOPE,
    DEFAULT_CANDIDATE_SETTING,
    DEFAULT_CANDIDATE_SOURCE,
    DEFAULT_CANDIDATE_SUMMARY_FILENAME,
    build_iohunter_temporal_edge_graph,
    run_iohunter_temporal_edge_candidate,
    write_iohunter_temporal_edge_candidate_exports,
)

__all__ = [
    "AccountMultigraphEdge",
    "FALLBACK_POLICY",
    "COORDINATION_DISCOVER_MODEL_VERSION",
    "COORDINATION_DISCOVER_TECHNOLOGY",
    "CoordinationDiscoverArtifactManifest",
    "DEPRECATED_COORDINATION_DISCOVER_MODEL_VERSIONS",
    "MODALITY_POLICY",
    "MODEL_INPUT_FEATURE_NAMES",
    "PAIR_EDGE_FULL_ACCOUNT_LIMIT",
    "PAIR_EDGE_MAX_PAIRS_PER_OBJECT",
    "PAIR_EDGE_NEIGHBOR_LIMIT",
    "SEMANTIC_TEXT_EMBEDDING_FIELDS",
    "TEXT_EMBEDDING_FEATURE_NAME",
    "DetectValidationRequest",
    "DetectValidationResult",
    "DiscoverResult",
    "DynamicDiscoverRequest",
    "EvidenceEdge",
    "EvidenceGraph",
    "EvidenceObject",
    "TemporalEdgeModelConfig",
    "TemporalEdgeSplit",
    "TemporalMAGNNConfig",
    "TemporalMAGNNTensors",
    "build_account_pair_edges",
    "build_evidence_graph",
    "build_matched_hard_negatives",
    "build_process_causal_experiment_report",
    "build_iohunter_temporal_edge_graph",
    "build_temporal_magnn_tensors",
    "fit_temporal_edge_model",
    "fit_temporal_edge_model_multi_seed",
    "export_coordination_result",
    "find_snapshot_artifact",
    "fit_temporal_magnn",
    "DEFAULT_CANDIDATE_ABLATION_METRICS_FILENAME",
    "DEFAULT_CANDIDATE_FAMILY",
    "DEFAULT_CANDIDATE_METHOD",
    "DEFAULT_CANDIDATE_METRICS_FILENAME",
    "DEFAULT_CANDIDATE_SCOPE",
    "DEFAULT_CANDIDATE_SETTING",
    "DEFAULT_CANDIDATE_SOURCE",
    "DEFAULT_CANDIDATE_SUMMARY_FILENAME",
    "load_discover_artifact",
    "partition_learned_graph",
    "run_temporal_edge_ablation_suite",
    "split_temporal_account_edges",
    "run_iohunter_temporal_edge_candidate",
    "run_detect_validation",
    "run_dynamic_discover",
    "validate_manifest_for_snapshot",
    "write_iohunter_temporal_edge_candidate_exports",
    "write_discover_artifact",
]
